language: java

jdk:
- oraclejdk7

script: mvn clean install deploy --settings src/main/config/travis-maven-settings.xml -U

env:
  global:
  - secure: UCT9KSGz79f8w93JfuYkeL3NjUAHUP5UxNt8xD95ZlkUf/SJHaBNb5tSU4EDU3gv5KHsQ6W+sK2Fj9kkCGlkUx9Fj0LVA1WoxR8WiEIF7bQtZP8dUFa/vbvq9WVhk8eC3DfOgBJNSrTrYUjVfXokNJ2py78bKuWs522mnpTtNqY=
  - secure: iqmje3FfxKXG4OyI0yGG1OIYqeZ5OaesiaBPH0W00B7nzBCNksLAwLmiriH9XZ/QAx/Qx4X4l0iUyNYnwS9fsT+jV+SaYqwQooAUlLfZh0iO6g5x+1NAQ3IDmCB2KA6BGzqz414mPScQyONrBa6+Yia7DbGxh7z2GLHonLTTMp0=
